"""Tests for the observed-premium checks in scripts/weekend_price_observed.py.

The script's claim is that the reconstructed prices the companion note is built
on are a change of units rather than an assumption, and that the premium effect
can be measured off traded prices with no pricer in the loop. Both claims are
testable on a synthetic book whose prices were generated by a known clock: the
reconstruction must come back exact, and the regression must recover the
coefficient the pricer predicts for it.
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))
import weekend_price_impact as P  # noqa: E402
import weekend_price_observed as O  # noqa: E402

from dbop import config, greeks  # noqa: E402


def book(R=0.6, n_days=260, v_wd=0.45, seed=0, linear=False,
         noise=0.0) -> tuple[pd.DataFrame, str]:
    """A traded book whose premia were generated by a known weekend clock.

    Each day carries its own level and several expiries with different weekend
    content; every strike is priced by Black-76 at the volatility the clock
    implies, and the premium is then written in the venue's own units so the
    conversion in ``derive`` has something to get wrong.
    """
    rng = np.random.default_rng(seed)
    cur = "SOL" if linear else "BTC"
    rows = []
    for i, day in enumerate(pd.date_range("2024-01-01", periods=n_days,
                                          freq="D", tz="UTC")):
        F = 100.0 * np.exp(rng.normal(0, 0.4))
        level = v_wd * np.exp(rng.normal(0, 0.2))
        # Maturities are drawn rather than fixed so that two expiries can land
        # in the same maturity bin carrying different weekend content. On the
        # real tape that overlap is what identifies the tight specification --
        # a venue listing one expiry per maturity would leave nothing to
        # compare within a cell.
        for e, (T_days, w) in enumerate(
                [(float(rng.uniform(0.3, 14.0)), float(rng.uniform(0, 1)))
                 for _ in range(8)]):
            T = T_days / config.YEAR
            sig = np.sqrt(level * float(P.damp(w, R)))
            # Quote noise enters as a volatility, not as a premium. The venue
            # publishes an implied volatility it inverted from its own price, so
            # the two are consistent by construction; perturbing the price alone
            # would build a disagreement into the fixture and the difference
            # test would be measuring the fixture.
            if noise:
                sig = sig * np.exp(rng.normal(0, noise))
            z = np.linspace(-2.4, 2.4, 26)
            # Both legs at every strike, as the real book trades them: the
            # in-the-money ones are what make the time-value convention
            # testable rather than vacuous.
            K = np.repeat(F * np.exp(z * sig * np.sqrt(T)), 2)
            cp = np.tile([1.0, -1.0], len(z))
            prem = greeks.price_usd(F, K, T, sig, cp)
            g = greeks.greeks(F, K, T, sig, cp)
            ad = np.abs(g["delta"])
            rows.append(pd.DataFrame({
                "iv2": sig ** 2, "logT": np.log(T_days), "T_days": T_days,
                "atmness": np.minimum(ad, 1.0 - ad),
                "is_call": (cp > 0).astype(float), "logm": np.log(K / F),
                "wknd_frac": w, "size": 1.0, "date": day, "F": F, "strike": K,
                "prem_quoted": prem if linear else prem / F,
                "expiry": i * 10 + e}))
    return pd.concat(rows, ignore_index=True), cur


def test_premium_units_differ_between_inverse_and_linear_books():
    """The one place the two conventions genuinely diverge."""
    d, _ = book(linear=False, n_days=5)
    inv = O.derive("BTC", d)
    lin = O.derive("SOL", d)
    assert np.allclose(inv["prem_obs"].to_numpy(),
                       lin["prem_obs"].to_numpy() * d["F"].to_numpy())


def test_reconstruction_is_exact_on_prices_the_pricer_generated():
    for linear in (False, True):
        d, cur = book(linear=linear, n_days=40)
        o = O.derive(cur, d)
        ok = ~o["tv_nonpositive"].to_numpy()
        assert np.allclose(o["err_tv"].to_numpy()[ok], 0.0, atol=1e-9), cur
        assert o["tv_recon"].sum() == pytest.approx(o["tv_obs"].sum(), rel=1e-12)


def test_time_value_is_the_premium_less_forward_intrinsic():
    d, cur = book(n_days=20)
    o = O.derive(cur, d)
    itm = o["intrinsic"].to_numpy() > 0
    assert itm.any()
    assert np.allclose(o["tv_obs"].to_numpy(),
                       o["prem_obs"].to_numpy() - o["intrinsic"].to_numpy())
    # And time value is what the pricer says the out-of-the-money twin costs.
    K, F = d["strike"].to_numpy(), d["F"].to_numpy()
    T = d["T_days"].to_numpy() / config.YEAR
    otm = np.where(K >= F, 1.0, -1.0)
    twin = greeks.price_usd(F, K, T, np.sqrt(d["iv2"].to_numpy()), otm)
    assert np.allclose(o["tv_obs"].to_numpy(), twin, atol=1e-9)


def test_a_mispriced_print_shows_up_as_reconstruction_error():
    d, cur = book(n_days=20)
    d.loc[:99, "prem_quoted"] *= 1.5
    o = O.derive(cur, d)
    assert (o.loc[:99, "err_tv"] < -0.1).mean() > 0.8
    assert o.loc[200:, "err_tv"].abs().max() < 1e-9


def test_fe_ols_recovers_a_planted_slope_and_reports_lost_variation():
    rng = np.random.default_rng(1)
    n, k = 20000, 200
    cell = rng.integers(0, k, n)
    day = cell % 50
    w = 0.4 * rng.normal(size=n) + cell / k          # correlated with the cell
    y = 3.0 + 2.0 * cell / k - 0.7 * w + rng.normal(0, 0.05, n)
    r = O.fe_ols(y, np.column_stack([w, rng.normal(size=n)]), cell, day)
    assert r["beta"] == pytest.approx(-0.7, abs=0.02)
    assert 0.0 < r["var_kept"] < 1.0
    # A coarser fixed effect leaves more of the regressor's variation standing.
    coarse = O.fe_ols(y, np.column_stack([w, rng.normal(size=n)]),
                      cell // 10, day)
    assert coarse["var_kept"] > r["var_kept"]


def test_the_standardized_bucket_cannot_be_moved_by_a_contract_s_own_weekend():
    """Why the buckets here are not the delta buckets of section 7.

    Delta is a function of the contract's own volatility, which the clock sets,
    so a delta bucket moves when the weekend fraction moves and conditioning on
    it conditions on the outcome. Standardizing against the day's own
    at-the-money level does not.
    """
    d, _ = book(n_days=30)
    base = O.fixed_bucket(d)
    # Re-quote a set of contracts as though they carried far more weekend. They
    # are chosen away from the money so the day's own at-the-money level -- the
    # scale the bucket is built on -- is untouched, which isolates exactly the
    # question: can a contract's own clock move its own bucket?
    hit = (d["atmness"] < 0.35).to_numpy()
    d2 = d.copy()
    d2.loc[hit, "iv2"] = d2.loc[hit, "iv2"] * 0.5
    moved = O.fixed_bucket(d2)
    lab = lambda s: pd.Series(s).astype(object).fillna("-").to_numpy()
    assert (lab(base)[hit] == lab(moved)[hit]).all()
    # The delta bucket of section 7, on the same perturbation, does move.
    ad = np.abs(greeks.greeks(d["F"], d["strike"],
                              d["T_days"] / config.YEAR,
                              np.sqrt(d2["iv2"]),
                              np.where(d["is_call"] > 0, 1.0, -1.0))["delta"])
    atm2 = np.minimum(ad, 1.0 - ad)
    b0 = pd.cut(d["atmness"], P.ATM_BINS, labels=list(P.ATM_LABELS),
                right=False)
    b1 = pd.cut(atm2, P.ATM_BINS, labels=list(P.ATM_LABELS), right=False)
    assert (lab(b0)[hit] != lab(b1)[hit]).any()


def test_the_observed_regression_recovers_what_the_pricer_predicts():
    """The test that matters: traded prices, no pricer in the outcome.

    The book was generated by a clock of 0.6, so the premium discount per unit
    of weekend exposure is a known quantity. The regression sees only prices and
    has to find it.
    """
    d, cur = book(R=0.6, n_days=400, noise=0.02, seed=7)
    o = O.derive(cur, d)
    r = O.premium_regression(cur, d, o, 0.6)
    tight = r[r["spec"] == "day x strike x maturity cell"]
    at = tight[tight["bucket"] == "at the money"].iloc[0]
    assert at["beta"] == pytest.approx(at["predicted"], abs=3 * at["se"])
    assert at["beta"] < 0
    # And a clock that does nothing leaves no premium effect to find.
    d0, cur0 = book(R=1.0, n_days=300, noise=0.02, seed=7)
    flat = O.premium_regression(cur0, d0, O.derive(cur0, d0), 1.0)
    row = flat[(flat["spec"] == "day x strike x maturity cell")
               & (flat["bucket"] == "at the money")].iloc[0]
    assert abs(row["beta"]) < 3 * row["se"]
    assert row["predicted"] == pytest.approx(0.0, abs=1e-12)


def test_observed_impact_uses_observed_money_for_its_base():
    d, cur = book(n_days=60)
    d["_all"] = "all"
    o = O.derive(cur, d)
    r = P.reprice(d, np.full(len(d), 0.6), np.full(len(d), 0.6))
    out = O.observed_impact(cur, d, o, r, ["_all"]).iloc[0]
    # Prices were generated by the pricer here, so the observed base and the
    # reconstructed one must agree to rounding -- which is what makes the two
    # sets of dollar columns comparable on the real tape.
    ok = ~o["tv_nonpositive"].to_numpy()
    assert out["tv_obs_usd_m"] * 1e6 == pytest.approx(
        float(r.loc[ok, "tv_usd"].sum()), rel=1e-9)
    assert out["discount_usd_m"] > 0
    assert out["price_cut_pct"] < 0
    assert out["gap_usd_m"] == pytest.approx(0.0, abs=1e-9)


def test_the_predicted_column_is_a_linearization_and_the_diff_column_is_the_test():
    """Why the wing rows are read off `beta_diff` and not off `predicted`.

    On a book the pricer itself generated there is by construction nothing for
    the observed series to disagree with, so `beta_diff` must be zero
    everywhere. `predicted` is not zero-error in the same way: it is a local
    derivative, the regression recovers a chord, and log premium is convex
    enough in the weekend fraction away from the money that the two part company
    badly in the wings. That gap is the estimator's linearization and nothing
    about any market, which is exactly why it is not the statistic the note
    quotes.
    """
    d, cur = book(R=0.6, n_days=500, noise=0.02, seed=11)
    r = O.premium_regression(cur, d, O.derive(cur, d), 0.6)
    t = r[r["spec"] == "day x strike x maturity cell"].set_index("bucket")
    for lab in ("at the money", "near", "wing", "far wing"):
        row = t.loc[lab]
        assert abs(row["beta_diff"]) < 3 * row["se_diff"], lab
    # And the local-derivative comparison fails in the far wing on the very
    # prices the pricer produced, which is the point.
    assert abs(t.loc["at the money", "t_vs_predicted"]) < 3
    assert abs(t.loc["far wing", "t_vs_predicted"]) > 5


def test_the_difference_test_catches_a_book_that_really_does_disagree():
    """Teeth: prices that carry an extra weekend discount must be detected."""
    d, cur = book(R=0.6, n_days=400, noise=0.02, seed=3)
    # Shave the distortion off time value rather than off the whole premium: an
    # in-the-money premium is mostly forward intrinsic, which no weekend belief
    # touches, and scaling that too would plant an effect of a different size in
    # every moneyness bucket.
    o0 = O.derive(cur, d)
    tv = o0["tv_obs"].to_numpy() * np.exp(-0.2 * d["wknd_frac"].to_numpy())
    prem = tv + o0["intrinsic"].to_numpy()
    d["prem_quoted"] = prem / d["F"].to_numpy()
    r = O.premium_regression(cur, d, O.derive(cur, d), 0.6)
    row = r[(r["spec"] == "day x strike x maturity cell")
            & (r["bucket"] == "at the money")].iloc[0]
    assert row["beta_diff"] == pytest.approx(-0.2, abs=0.02)
    assert abs(row["t_diff"]) > 5
